#Set cluster queue for team-c. Cohort: team-cg
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: team-c-cq
spec:
  namespaceSelector: {} # Available to all namespaces
  cohort: "team-cg"
  queueingStrategy: StrictFIFO # Workloads are ordered first by priority
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 1
      - name: "memory"
        nominalQuota: 1Gi
